/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wifiyou_framework_udid_UDIDUtil */

#ifndef _Included_com_wifiyou_utils_UDIDUtil
#define _Included_com_wifiyou_utils_UDIDUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wifiyou_framework_udid_UDIDUtil
 * Method:    generateUDID
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wifiyou_utils_UDIDUtil_generateUDIDNative
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_wifiyou_framework_udid_UDIDUtil
 * Method:    isUDIDValid
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wifiyou_utils_UDIDUtil_isUDIDValidNative
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
